baseURL = "https://chris-s-friedman.com/"
defaultContentLanguage = "en"
languageCode = 'en-us'
title = "Chris Friedman's Blog"
theme = "gokarna"
enableRobotsTXT = true
enableEmoji = true

[menu]

[[menu.main]]
# Unique identifer for a menu item
identifier = "posts"
url = "/posts/"
# You can add extra information before the name (HTML format is supported), such as icons
pre = ""
# You can add extra information after the name (HTML format is supported), such as icons
post = ""
# Display name
name = "Posts"
# Weights are used to determine the ordering
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifer = "About"
name = "About"
url = "/about"
weight = 3

[[menu.main]]
identifer = "Newsletter"
name = "Newsletter"
url = "/newsletter"
weight = 3

[[menu.main]]
identifier = "github"
url = "https://github.com/chris-s-friedman"
weight = 4
pre = "<span data-feather='github'></span>"

[[menu.main]]
identifier = "linkedin"
url = "https://www.linkedin.com/in/christopher-friedman-36265664/"
weight = 5
pre = "<span data-feather='linkedin'></span>"

[[menu.main]]
weight = 6
identifier = "resume"
name = "Resume"
# pre = "<span data-feather='file-text'></span>"
url = "https://cv.chris-s-friedman.com/files/Friedman_Resume.pdf"

[params]
description = "Usually writing about data, sometimes about mistakes, and occasionally about other things."
favicon = "https://res.cloudinary.com/chrissfriedman/image/upload/v1512174331/favicon_j0grb0.ico"
showPostsOnHomePage = "recent"
accentColor = "#73d2de"
accentColor2 = "#ffbc42"
avatarURL = "https://res.cloudinary.com/chrissfriedman/image/upload/c_scale,w_1480/v1512174332/cover_kvxrzm.jpg"
footer = "Chris Friedman"
avatarSize = "size-m"
css = ['css/custom.css']

[permalinks]
post = "/:year/:month/:slug/"

# [module]
# [[module.imports]]
# path = "github.com/bep/hugo-mod-misc/render-hooks"
[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
